<?xml version="1.0" encoding="utf-8"?><Database Name="ShoppinCart" Class="ShoppingCartDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\ShoppinCart.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="MainFrame.Properties.Settings" SettingsPropertyName="ShoppinCartConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="C_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="C_Password" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="C_Firstname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="C_Lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="C_Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="C_Phone" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="C_Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="A_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="A_Password" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="A_Firstname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="A_Lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="A_Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="A_Phone" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="A_Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="Cat_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cat_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cat_Des" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Category_Product" Member="Products" ThisKey="Cat_ID" OtherKey="Cat_ID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="P_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="P_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="P_Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="P_Stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cat_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="P_Des" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Category_Product" Member="Category" ThisKey="Cat_ID" OtherKey="Cat_ID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Transaction]" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="P_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="P_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cat_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cat_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Total" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="T_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>